### ISSUE TITLE
Thoughts on current challenges and open questions

### ISSUE THREAD

**Issue by dcodeIO** [ColinEberhardt/assemblyscript-temporal#2]
> AssemblyScript doesn't support union types. What is the best way to support this API?

One solution is to make the functions generic, using an unrestricted `T`, and utilize static* type checks within the function:

```ts
function from<T>(input: T): PlainDate {
  if (isString<T>()) {
    ...
  } else {
    if (input instanceof PlainDateTime) {
      ...
    } else {
      throw new Error("unexpected type");
    }
  }
}
```

(*) Oftentimes, the `instanceof` checks can be statically evaluated as well. Not always, though, for example if an upcast is required, then yielding a runtime check in addition.

The function can then be called without a type argument, letting the compiler infer from the input:

```ts
from('2006-08-24');
```

> AssemblyScript doesn't support object literals. What is the best way to support this API?

It has partial support for constructing classes from object literals. To give an example:

```ts
class MyClass {
  years: i32 = 0,
  months: i32 = 0
}
function add(input: MyClass): void {
  ...
}
```

can be called as

```ts
add({ years: 20, months: 4 });
```

It is likely that the current implementation of object literals has edge cases we'd have to tackle, though.

**Comment by ColinEberhardt** [comment]
Thanks - that's really helpful, and looks like a potential solution that allows this library to have an API that is very close to the JS equivalent.

**Comment by ColinEberhardt** [comment]
Unfortunately it looks like the use of `DateLike` with the unrestricted generic type requires a cast ...

~~~
class DateLike {
  year:i32 = -1;
  month:i32 = -1;
  day:i32 = -1;
}

class PlainDate {
  year:i32;
  month:i32;
  day:i32;

  static from<T>(date: T): PlainDate {
    return new PlainDate();
  }
}

const foo = PlainDate.from(({year: 22}) as DateLike);
//                                      ^^^^^^^^^^^^
~~~
see:
https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRGF0ZUxpa2UgewogIHllYXI6aTMyID0gLTE7CiAgbW9udGg6aTMyID0gLTE7CiAgZGF5OmkzMiA9IC0xOwp9CgpjbGFzcyBQbGFpbkRhdGUgewogIHllYXI6aTMyOwogIG1vbnRoOmkzMjsKICBkYXk6aTMyOwoKICBzdGF0aWMgZnJvbTxUPihkYXRlOiBUKTogUGxhaW5EYXRlIHsKICAgIHJldHVybiBuZXcgUGxhaW5EYXRlKCk7CiAgfQp9Cgpjb25zdCBmb28gPSBQbGFpbkRhdGUuZnJvbSgoe3llYXI6IDIyfSkgYXMgRGF0ZUxpa2UpOwojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgdGVzdCgke2l9KSA9ICR7ZXhwb3J0cy50ZXN0KGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==

**Comment by kungfooman** [comment]
What about variadic methods?

https://github.com/tc39/proposal-temporal/blob/main/polyfill/lib/intl.mjs#L91

**Comment by SebastianSpeitel** [comment]
> Unfortunately it looks like the use of `DateLike` with the unrestricted generic type requires a cast ...

Providing the type seems to work as well:
```ts
const foo = PlainDate.from<DateLike>({year: 22});
```

**Comment by ColinEberhardt** [comment]
> Providing the type seems to work as well

Good point, that's not so bad

**Comment by dcodeIO** [comment]
The challenge in `PlainDate.from({year: 22})` is that an object literal can only be used with a class type, but `T` can be anything, so the compiler would have to guess. One potential solution that comes to my mind is that we could try to implement type parameter defaults, like `function from<T = DateLike>( ... ) ...` as a fallback to use when `T` can otherwise not be inferred.
